sudo: required
services:
  - docker

before_install:
  - docker build -t martinstaebler/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true martinstaebler/react-test npm test

after_success:
  - docker build -t martinstaebler/multi-client ./client
  - docker build -t martinstaebler/multi-nginx ./nginx
  - docker build -t martinstaebler/multi-server ./server
  - docker build -t martinstaebler/multi-worker ./worker

  # Log into Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # push to docker hub
  - docker push martinstaebler/multi-client
  - docker push martinstaebler/multi-nginx
  - docker push martinstaebler/multi-server
  - docker push martinstaebler/multi-worker


